const fs = require('fs');
const https = require('https');
const path = require('path');

const HIRAGANA_URL = 'https://cdn.jsdelivr.net/npm/kana-svg-data/dist/allHiragana.json';
const KATAKANA_URL = 'https://cdn.jsdelivr.net/npm/kana-svg-data/dist/allKatakana.json';
const OUTPUT_FILE = path.join(__dirname, '../src/data/kanaStrokes.ts');

function fetchJson(url) {
    return new Promise((resolve, reject) => {
        https.get(url, (res) => {
            let data = '';
            res.on('data', (chunk) => data += chunk);
            res.on('end', () => {
                try {
                    resolve(JSON.parse(data));
                } catch (e) {
                    reject(e);
                }
            });
        }).on('error', reject);
    });
}

async function main() {
    try {
        console.log('Fetching Hiragana data...');
        const hiraganaData = await fetchJson(HIRAGANA_URL);
        console.log(`Fetched ${hiraganaData.length} Hiragana entries.`);

        console.log('Fetching Katakana data...');
        const katakanaData = await fetchJson(KATAKANA_URL);
        console.log(`Fetched ${katakanaData.length} Katakana entries.`);

        const outputData = {};

        // Helper to process list
        const processList = (list) => {
            list.forEach(char => {
                const charStr = String.fromCharCode(char.charCode);
                const outlines = char.strokes.map(s => s.value);
                // The clipPaths in the source are the centerlines (skeletons) used for animation
                const paths = char.clipPaths.map(s => s.value);

                outputData[charStr] = {
                    outlines,
                    paths
                };
            });
        };

        processList(hiraganaData);
        processList(katakanaData);

        const fileContent = `/**
 * Optimized Kana Stroke Data
 * Source: kana-svg-data (KanjiVG based)
 * Generated by scripts/fetchKanaData.js
 */

export interface KanaStrokeData {
    outlines: string[];
    paths: string[];
}

export const KANA_STROKES: Record<string, KanaStrokeData> = ${JSON.stringify(outputData, null, 2)};
`;

        fs.writeFileSync(OUTPUT_FILE, fileContent);
        console.log(`Successfully wrote data to ${OUTPUT_FILE}`);

    } catch (error) {
        console.error('Error:', error);
        process.exit(1);
    }
}

main();
